POST https://localhost:5001/api/todo/create
Content-Type: application/json

{
    "ToDoName": "NomeTesteToDo",
    "Description": "TesteDescrição ToDo"
}

###
GET https://localhost:5001/api/todo/list

###
PUT https://localhost:5001/api/todo/update/2
Content-Type: application/json

{
    "ToDoName": "NomeTesteToDo Alterado"
}
###
DELETE https://localhost:5001/api/todo/delete/1