POST https://localhost:5001/api/todo/create
Content-Type: application/json

{
    "ToDoName": "Teste numero 3",
    "Description": "Descrição do item novo 6",
    "ToDoDate": "2021-11-25T20:25:57.8002055",
    "CategoryId": 3,
    "allDay": true
}

###
GET https://localhost:5001/api/todo/list

###
PUT https://localhost:5001/api/todo/update/27
Content-Type: application/json

{
    "allDay": true,
    "CategoryId": 4
}

###
DELETE https://localhost:5001/api/todo/delete/10

###
POST https://localhost:5001/api/category/create
Content-Type: application/json

{
    "CategoryName": "Nome Teste 2 Categoria"
}

###
GET https://localhost:5001/api/category/list
